# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_status', '0001_initial'),
        ('apps_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.ForeignKey(default='Kosong', on_delete=django.db.models.deletion.CASCADE, to='apps_status.Status'),
        ),
    ]
