# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_profile', '0002_auto_20171212_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
