# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_profile', '0003_auto_20171212_2121'),
        ('apps_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(default='kosong', on_delete=django.db.models.deletion.CASCADE, to='apps_profile.User'),
        ),
    ]
